FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json tsconfig.json prisma.config.ts ./
COPY prisma ./prisma

RUN npm ci

COPY src ./src

RUN npm run build

#----- Production Stage ----

FROM node:20-slim AS runner
WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./

EXPOSE 3002

USER node

CMD [ "node", "dist/index.js" ]